version: '3'

services:
  traefik:
    image: traefik # The official Traefik docker image
    container_name: traefik
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "88:80"     # The HTTP port
      - "8888:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    restart: unless-stopped